# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dmsibi <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/05/24 10:01:47 by dmsibi            #+#    #+#              #
#    Updated: 2018/05/24 10:20:16 by dmsibi           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME: Libft.a

SOURCES: ft_islower.c ft_putchar.c ft_putstr.c ft_putnbr.c ft_islower.c ft_isspace.c ft_isalpha.c ft_isdigit.c ft_alnum.c ft_isascii.c ft_atoi.c ft_strlen.c ft_strcat.c ft_strcpy.c ft_strcmp.c ft_strdup.c 

OBJECTS: 
	%.o = %.c $@ $< $(HEAD)
HEAD: libft.h

CC: 
	gcc -c -o 


FLAGS: 
	-Wall -Werror -Wextra
